### ISSUE TITLE
Error when using single quotes on README

### ISSUE THREAD

**Issue by anahelenasilva** [herbsjs/herbsshelf#39]
**Describe the bug**
When using single quotes on readme.md file, herbsshelf crashes, as shown bellow:

**To Reproduce**
1. Clone this [repo](https://github.com/anahelenasilva/herbs-shelf-test)
2. Run `npm install`
3. Run `npm start:dev`
4. Access the herbsshelf [endpoint](http://localhost:3004/herbsshelf)
5. See the error on devtools

I noticed that if you wrap someting in single quotes (like 'this'), the error occurs. But if I remove them, the error stops.

**Expected behavior**
Herbsshelf should work whether or not I use single quotes in the readme file.

**Screenshots**
![image](https://user-images.githubusercontent.com/10438122/164058024-8ff4bfe0-9051-4eb0-9ba3-4207050a3965.png)

**Comment by italojs** [comment]
do you have some idea about how to fix it ?

**Comment by gustavobigardi** [comment]
> do you have some idea about how to fix it ?

I sent a PR in order to fix it. The issue was a replace for single quotes, replacing just the first occurrence of single quotes. I replaced it by using a regex to replace all the occurrences (can't use replaceAll, since the lib has compatibility with Node V14, that does not support the replaceAll method for strings)
